### ISSUE TITLE
Enable lwlog_info and others to accept const char*

### ISSUE THREAD

**Issue by TBye101** [Akagi201/lwlog#1]
To make the library MUCH easier to use, you could enable your logging methods to accept const char (pointer). Converting from const char (pointer) to const char[] is practically impossible for the unexperienced.

**Comment by Akagi201** [comment]
@SneakyTactician Hi, Could you give a PR or sample code to explain it?

**Comment by TBye101** [comment]
Sure, I will do that tomorrow.

Thomas
________________________________

**Comment by TBye101** [comment]
I know that your library is a C based library, but it is also usable from C++. The string class is often used in C++ to hold strings, and when you convert it to a more C style way of things to interact with your library via c_str(), you end up with a const char (pointer). Your library accepts const char[].

	string* a = new string("TEST");
	lwlog_info(a->c_str());

I searched the internet long and hard on how to convert const char (pointer) to const char[], but to no avail. This is just a suggestion. If I had the C skills, I would give you a pull request with working code. Of course, if I had the C skills, I wouldn't have this problem.

**Comment by Akagi201** [comment]
@SneakyTactician 
```
    const char *ch = "aaaaaaaaa";
    lwlog_emerg("%s", ch);
```
You can use like this.

**Comment by TBye101** [comment]
Ah, thanks!

Thomas
________________________________
