### ISSUE TITLE
Request: Move license text to front matter of "lwlog.h"

### ISSUE THREAD

**Issue by strazto** [Akagi201/lwlog#2]
Hi - 
I use this logging header frequently in c projects because it's portable and doesn't have runtime dependencies. 

Usually this basically involves copying the header file into my project. 
To make compliance with the licensing easier, would you be able to copy the licensing front matter to the actual source file?

I also wonder if you'd be interested in changing to MIT, just because it's shorter but practically the same, albeit the modification clauses, which I'd be surprised if you were very concerned with.

Cheers!

**Comment by Akagi201** [comment]
changed to MIT
